services:

  front-nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/FrontNginx.dockerfile
    container_name: frontNginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network

networks:
  amalfis-network:
    driver: bridge
