services:
  nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/nginxFront.dockerfile
    image: feljohnny/nginx-frontend
    container_name: nginx-amalfis-denuncia
    ports: 
      - "80:80"
    networks:
      - amalfis-network

networks:
  amalfis-network:
    driver: bridge
