services:
  nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/nginxFront.dockerfile
    image: feljohnny/nginx-frontend
    container_name: nginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/denuncia.amalfis.com.br
        target: /etc/letsencrypt/live/denuncia.amalfis.com.br
        read_only: true

networks:
  amalfis-network:
    driver: bridge
