services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/docker/frontend.dockerfile
    container_name: frontend-amalfis-denuncia
    networks:
      - amalfis-network

  nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/nginx.dockerfile
    container_name: nginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network

networks:
  amalfis-network:
    driver: bridge
