services:

  backend-nginx:
    build: 
      context: .
      dockerfile: ./backend/docker/Backend.dockerfile
    container_name: backendNginx-amalfis-denuncia
    env_file:
      - .env
    networks:
      - amalfis-network

  front-nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/FrontNginx.dockerfile
    container_name: frontNginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network

networks:
  amalfis-network:
    driver: bridge
