
services:
  backend-nginx:
    build: 
      context: .
      dockerfile: ./backend/docker/Backend.dockerfile
    container_name: backendNginx-amalfis-denuncia
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - amalfis-network

  front-nginx:
    build: 
      context: .
      dockerfile: ./frontend/docker/FrontNginx.dockerfile
    container_name: frontNginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network
    depends_on:
      - backend-nginx
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/var/lib/letsencrypt
      - certbot-config:/etc/letsencrypt/config

networks:
  amalfis-network:
    driver: bridge

volumes:
  certs:
  certs-data:
  certbot-config:
