services:
  frontend:
    build: 
      context: ./docker
      dockerfile: frontend.dockerfile
    container_name: frontend-amalfis-denuncia
    networks:
      - amalfis-network

  nginx:
    build: 
      context: ./docker
      dockerfile: nginx.dockerfile
    container_name: nginx-amalfis-denuncia
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - amalfis-network

networks:
  amalfis-network:
    driver: bridge
